### PR TITLE
Add in panel collapsing and onPanelCollapse() callback

### PR DESCRIPTION
**Pull request by tnrich**
Hey @leefsmp this PR addresses https://github.com/leefsmp/Re-Flex/issues/50
Reflex container now accepts a new props `onPanelCollapse` that can be used like this:

`<ReflexContainer onPanelCollapse(panelProps => {doSomethingWithThePanels})/>`

As you can see the PR still has some rough edges (like adding a dependency to lodash). If you could play around with it, I'd love any input you have as well as any help making it better you might be able to provide. 

Here is a gif of it working in my project locally: 

untitled

### CODE REVIEW

**Comment by leefsmp** [comment]
Thanks for taking time to do a PR, however I'm a bit reluctant to include that in the main branch: most developers might not need/want collapsible panels and your code seems to handle only the scenario where you have a single collapsible panel. What if you have a container with 3 panels, the left one and the right one can be collapsed but not the middle one? Handling such scenario would require a significantly more complex logic.

My suggestion would be to use size aware `ReflexElements` (see [demo](https://leefsmp.github.io/Re-Flex/index.html#demo7)) or Splitter event `onResize` then check if the size of the element you want to collapse, if below the threshold use state of a custom component to toggle rendering of the whole `ReflexElement`.

I will try to come up with a demo example and add it to the doc.

**Comment by leefsmp** [comment]
I've added the [Collapsible Panels demo](file:///Users/leefsmp/Dropbox/projects/adn/re-flex/index.html#demo9), which doesn't require any modification to the lib but just a bit of custom logic. Can you take a look and let me know what you think?

**Comment by tnrich** [comment]
I will soon. Thanks for doing that!

**Comment by tnrich** [comment]
Hey @leefsmp thanks for that demo! Much appreciated. I am not sure if you noticed in the gif I posted that with my solution the collapse is not final. You can see what I mean here as well if you drag a panel to the side until it collapses but, without lifting your finger, drag it back:
http://teselagen.github.io/openVectorEditor/

I am curious if you think that kind of functionality could be created using your Collapsible element? Thanks in advance!

**Comment by leefsmp** [comment]
It's not doable with the current approach because the splitter stops to be rendered as soon as the panel collapses. In order for it to work the splitter must remain at least until the user is not holding mouse button, so in case there is a drag in the increasing direction, the splitter is still active and panel can be resized.

I will see if I can come up with a decent solution on the example.

**Comment by leefsmp** [comment]
I don't see an easy way to handle the close/reopen workflow in the current state of the package. Some extra logic would need to be added to the custom implementation but it would be tricky to do that in an elegant way :( ... I will not merge your PR for the time being as it can handle only the case where one has just 2 panels.

**Pull request closed without merging**
