### PR TITLE
Added link to CodecastJS user of Re-Flex

### PR DESCRIPTION
**Pull request by scottburch**
Thank you for your excellent library.  It was a huge help.  

I have added a link to the README.md to my site designed to provide JS training and documentation for libraries complete with live code examples with audio.

I am looking for libraries to add to the site.  I would be happy to add documentation for Re-flex as well if that would help.  Let me know if this is OK with you.

### CODE REVIEW

**Comment by leefsmp** [comment]
Hi Scott, sure perfectly fine with me.
Thanks!

**Comment by scottburch** [comment]
I added a component to work with Reflex and I wanted to check with you because I am thinking about trying to add it to a fork and do a pull request.

Oh, and I am still planning on putting together a codecast about Reflex, I am cleaning up a few bugs in the tool first.

However, In my project I needed another component which had a fixed size, but I did not know what it was in advance.  It depended on the size of the contents.  I tried several things but it looks like you are playing with the children of the <ReflexContainer> so it needed to have certain properties and maybe methods, I have not looked to deeply at it yet.

I’m calling it <ReflexFixed> for the moment.  I guess because of the way you are doing things it works just fine without a lot of work.

This is what I threw together quickly.

import Component from 'components/Component'

export default class ReflexFixed extends Component {
    render() {
        const {maxSize, minSize, children, ...props} = this.props;
        return <div {...props}>{children}</div>;
    }
}

—— I use it like this ——
<ReflexContainer orientation="vertical">
    <ReflexFixed style={{overflow: 'auto', minWidth: 200}}>
        <SectionList codecast={codecast} onSectionChange={this.onSectionChange.bind(this)} activeSectionId={this.state.sectionId}/>
    </ReflexFixed>
    <ReflexElement flex={1}>
So, I have a section that flexes with the size of the content and another that takes the rest of the spaceLike
Like I said, I have not put a lot of time looking into it.  Let me know if this is a component that makes sense for Reflex.  If you want the name changed, or just an option off of <ReflexElement>, whatever.  It seemed like it was different enough, because it’s size is not set by the parent container that it should be its own component.

Thanks again for such a great tool.

**Comment by leefsmp** [comment]
It's not clear to me what you mean exactly by a fixed size which depends on the size of the contents, that's what the flex property does by definition: flex = 0.2 means the component will take 20% of its parent container and if you do not use a splitter it will have  a fixed size as long as the parent doesn't get resized. If you use a container with 2 elements and one has flex=1 then it will take all the space so I don't get the idea there. Also you can use property `minSize` on `ReflexElement` and don't have to set `minWidth` through the style. If you want a component to have a fixed size in pixels, you can set both `minSize` and `maxSize` but you need to know that size in advance. You can use `react-measure` in order to get that if the size is determined at render time.

You can take a look  the [controlled element demo ](https://leefsmp.github.io/Re-Flex/index.html#demo6) for an example on how to wrap a `ReflexElement` inside a custom component.

Hope that helps

**Comment by scottburch** [comment]
Thanks for the reply.  Yes, putting flex={1} on the right pane does not do what I want.  Below I have put two images.  One with flex=1 on the right hand component and the second one with <ReflexFixed/> for the left side element. 

The second one is laying out properly while the first one is the 200px I put in minSize={200} so it is chopping off the titles.

I don’t want to fix the size and I don’t want to put a flex percentage.  I like that it just lays out depending on the size of the contents of the left pane.

I got this idea from the library I was using before I found Reflex which only. Has <Layout>, <Fixed> and <Flex>.  That is how it works.  However, it is not as nice as Reflex and does not have the sliders.

This is a case that is not covered in your examples.  (Which were very helpful BTW).

Scott

**Comment by leefsmp** [comment]
I don't see any image in your comments... and I can't figure out what you are looking for exactly. An element can only either have a fixed size or have a flex percentage of the parent, there is no other way. If you have two elements within a container and set the size of one of them, it will determine the size of the second, in such a way that the sum of both fills up the entire space of the parent. 

As far as I know there is no way to size a component based on the size of its content because the content is rendered after the parent, so we are in a chicken-and-egg configuration here. I'm pretty sure you are misunderstanding something here and there is no need for a `ReflexFixed` wrapper component...

**Comment by scottburch** [comment]
Thanks for the reply.  I appreciate it.  I am happy to keep using my component locally.  I just wanted to check with you before putting  in the effort to do a pull request.

**Pull request merged**
