### PR TITLE
Adding option to not propagate height/width to ReflexElement child

### PR DESCRIPTION
**Pull request by tnrich**
I was having an issue where I wanted the width of my components to be automatically updated, but not the height so I added some code to allow me to do that. Namely resizeHeight and resizeWidth booleans.

I'm using a fork of this repo with these changes and it fixes the issue I was seeing with the height. 
https://www.npmjs.com/package/tg-react-reflex

I wasn't quite sure how to update the documentation to show these new options so I thought I'd ask for your help doing so. 

Thanks! 

Love this repo btw

### CODE REVIEW

**Comment by leefsmp** [comment]
Cool, thanks! Do you think you can come up with a simple example that illustrates how it can be useful? Then I can add it to the samples page. The other "advanced" options {renderOnResizeRate, propagateDimensions, renderOnResize} have also been added for my own needs and are pretty specific. I've been lazy to document those as well :s Should do at some point ...

**Comment by tnrich** [comment]
@leefsmp awesome! Thanks for merging that so quickly.

My particular use case was that the height measurement was causing an infinite loop on certain browsers and I was only interested in the width measurement. So I don't have a great example except for fixing that kind of unique bug.

**Comment by leefsmp** [comment]
Could the issue you mention be related to that one https://github.com/leefsmp/Re-Flex/issues/38?

**Comment by tnrich** [comment]
@leefsmp I am not 100% sure but I don't believe that it is related. I looked that the computeFlexDataRec function but couldn't quite tell exactly what it is trying to do. Could you explain that a little bit more for me and I might be able to tell you if it is involved? 

I am pretty sure in my case the loop was contained within the ReflexElement. It was having setState() called with a new height which would cause a re-render and the react-measure component would measure the resulting component and detect that the height had changed which would cause setState() to be called again. 

I'm not sure where the computeFlexDataRec would fit in the above loop.

**Comment by tnrich** [comment]
Also, on a side note, let me know when you publish the new code to npm. Thanks!

**Comment by leefsmp** [comment]
Done react-reflex@2.1.0 on npm now

**Comment by leefsmp** [comment]
`computeFlexDataRec` is a recursive function called internally by `ReflexContainer.computeFlexData`: this method computes initial flex data for each child element of a container based on provided `flex` properties if any. By default each `ReflexElement` gets evenly arranged within its container if no `flex` is specified, otherwise the container will attempt to accommodate  initial flex values for each element. In case the computed flex value for a component is smaller or bigger than the imposed flex in the element property, the logic will call recursively that method until it can solve the imposed constraints. As mentioned in the issue I was testing the component on Ubuntu against the specified version of Firefox and couldn't reproduce the infinite loop. Only problem I can think about would be if the user is specifying various flex properties as input which cannot be satisfied (over-constrained system), but that would be a programmer error.

**Comment by tnrich** [comment]
Is this talking about the flex grow/shrink properties specifically? Those are the only flex properties I'm aware of which have number values.

**Comment by tnrich** [comment]
Okay, that makes sense. If I have the time I'll poke around and see if that might be the issue but unfortunately I can't reproduce it on my own machine so it is a little difficult for me to test. Also thanks for publishing :)

**Pull request merged**
