### PR TITLE
Replacing componentWillReceiveProps by componentDidUpdate

### LINKED ISSUE #82: Warning: componentWillReceiveProps has been renamed, and is not recommended for use.
Hello!
My browser keeps yelling this warning.

´´´
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReflexElement
´´´ 

Can I help you update this or are you already working on it?

### PR DESCRIPTION
**Pull request by IamFonky**
Seem to work fine without warnings now fixes #82

### CODE REVIEW

**Comment by leefsmp** [comment]
The proper way to migrate from `componentWillReceiveProps` is actually to use the new `getDerivedStateFromProps ` method. See [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#examples) for more info. 

Even if replacing with `componentDidUpdate` works, I don't think it is an optmized way of doing things.

**Comment by IamFonky** [comment]
Thx for your review @leefsmp. I started using React with hooks and I'm not very good with React classes lifecycles.
I use getDerivedStateFromProps for the ReflexContainer but I read that it's better to use componentDidUpdate with data fetching.

https://github.com/facebook/react/issues/13541

Is this better?

**Comment by leefsmp** [comment]
I took a closer look at using `getDerivedStateFromProps` and in the current state of the code it require a lot of modifications inside `ReflexContainer` and it is also tricky because this is a static method, so it doesn't have access to `ReactDOM.findDOMNode` so I would need more time to migrate to it. 

I was publishing v `3.0.17` with a similar fix than what you did in this PR but it actually breaks my own app where the layout is significantly more complex than in the demos, including some animations with the panes.

I will need more time to see how I can migrate to `getDerivedStateFromProps` in a proper way.

**Comment by IamFonky** [comment]
Ok!
Do you want me to try with hooks?

**Comment by leefsmp** [comment]
btw - I replaced `componentWillReceiveProps` by `UNSAFE_componentWillReceiveProps` which hopefully suppresses the warnings in v3.0.18.

Feel free if you want to try hooks but the internal logic in `ReflexContainer` is a bit tricky, you need to make sure you understand correctly what's going on otherwise complex use of the component in some layouts will break.

**Comment by IamFonky** [comment]
Allright thank you for your help!
I'll try that soon.

**Comment by leefsmp** [comment]
There is no async data fetching here as the layout computes it's state directly from the props but what is more complex than in other react components is that the logic has to solve some constraints to compute correct size of each element and it also has to access the DOM element to find out the size of the container.

**Pull request closed without merging**
